services:
  iaspmal_2026-prod:
    container_name: iaspmal_2026-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    env_file:
      - .env
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
