services:
  iaspmal_2026-prod:
    container_name: iaspmal_2026-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
