import React from 'react';

const CallForParticipation = ({ lang }) => {
  const content = {
    es: {
      intro: `En tiempos en los que nociones que dábamos por sentadas adquieren significados y valores hace poco impensables; cuando resulta difícil establecer siquiera mínimos compartidos para la convivencia en diversos niveles y contextos; cuando los horizontes de sentido parecen reducirse a los horizontes de negocio y conceptos como dignidad y justicia son tachados de "radicales"; cuando la violencia, la precariedad y los despojos no dejan de profundizarse en toda América Latina pero también emergen y persisten iniciativas que apuestan por otras formas de estar en el mundo, el XVII Congreso de la rama latinoamericana de la IASPM convoca a reflexionar sobre las músicas populares desde las preguntas éticas y políticas que atraviesan nuestra vida en común.`,
      intro2: `Polémicas recientes como la generada por "+57" en Colombia o los corridos tumbados en México nos recuerdan que el campo musical no puede pensarse como autónomo de los conflictos y tensiones sociales. En este marco, invitamos a reflexionar y debatir sobre las intersecciones entre ética, política y música popular, así como sobre los temas que se tratarán en los 19 simposios que vertebrarán el Congreso, que tendrá lugar del 28 de septiembre al 2 de octubre de 2026 en el centro histórico de San Cristóbal de Las Casas, Chiapas.`
    },
    en: {
      intro: `At a time when notions we took for granted are acquiring meanings and values that were until recently unthinkable; when it is difficult to establish even minimum shared grounds for coexistence at various levels and in various contexts; when horizons of meaning seem to be reduced to business horizons and concepts such as dignity and justice are dismissed as "radical"; when violence, precariousness, and dispossession continue to deepen throughout Latin America, but initiatives that champion other ways of being in the world also emerge and persist, the XVII Congress of the Latin American branch of the IASPM calls for reflection on popular music from the perspective of the ethical and political questions that permeate our shared life.`,
      intro2: `Recent controversies such as that generated by "+57" in Colombia or the corridos tumbados in Mexico remind us that the musical field cannot be thought of as independent of social conflicts and tensions. In this context, we invite reflection and debate on the intersections between ethics, politics, and popular music, as well as on the topics that will be addressed in the 19 symposia that will comprise the Congress, which will take place from September 28 to October 2, 2026, in the historic center of San Cristóbal de Las Casas, Chiapas.`
    }
  };

  const t = content[lang];

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-8 shadow-sm">
      <div className="max-w-4xl mx-auto space-y-6">
        <p className="text-gray-700 text-justify leading-relaxed">
          {t.intro}
        </p>
        <p className="text-gray-700 text-justify leading-relaxed">
          {t.intro2}
        </p>
      </div>
    </div>
  );
};

export default CallForParticipation;
